spring:
  application:
    name: weather-app
#  main:
#    banner-mode: "off"
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./data/weatherdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

logging:
  level:
    root: INFO
#  pattern:
#    console: "\u001b[0;34;1m%d{HH:mm:ss} \u001b[0;32;1m%-5level \u001b[0;33;1m%logger{36} - \u001b[0;37;1m%msg%n"

vaadin:
  launch-browser: true









